### ISSUE TITLE
i have a problem EVERYTIME i use your program

### ISSUE THREAD

**Issue by Charliebaby019** [Sean-Bradley/StatsVR#18]
and that problem is , each and every time i use it .......

I just want to THANK YOU for your work in developing it and delivering it to the public.
I use it all the time and i think its pretty nifty there buddy.
I saw you suggested it on a question about remote debugging on discourse.threejs.org
and saw that  they just rudely passed on the help, and that erked me quiet a bit.
i dunno. call be sensative but
i use it often for debugging and have no complaints.
sure sure, i still run into [object object] difficulties and its not exactly a full debugging solution..
but without statsVR, id be very very very much more frustrated with webxr.

and im sorry,buuuuut i don't really know where else to compliment you on this work so....
filling it under you github issues will get this where it needs to be
thanks again!
and best wishes

**Comment by Sean-Bradley** [comment]
cool, thanks.
